dist: trusty
sudo: enabled
language: cpp

before_script:
  - mkdir avr_build
  - mkdir build

before_install:
  - sudo apt-get -qq update
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install -y cmake

matrix:
  include:
    # Unit tests on default compiler
    - env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script:
        - cd build
        - cmake ../ -DUNIT_TESTING=ON
        - make -j2 && ctest -V

    # AVR build
    - env:
        - MATRIX_EVAL="CC=avr-gcc && CXX=avr-g++"
      addons:
        apt:
          packages:
            - arduino
            - gcc-avr
            - binutils-avr 
            - avr-libc
      
      script:
        - cd avr_build
        - cmake ../
        - make -j2

    # Unit tests on latest compiler
    - env:
        # According to the docs this is the correct way to set CC and CXX
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7

      script:
        - cd build
        - cmake ../ -DUNIT_TESTING=ON
        - make -j2 && ctest -V